[platformio]
default_envs = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1]
platform = espressif32@6.11.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 921600
upload_speed = 921600

lib_deps =
  adafruit/Adafruit BusIO@1.17.4
  adafruit/Adafruit ADS1X15@2.6.2
  adafruit/RTClib@2.1.4

build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
build_unflags =
  -std=gnu++11

[env:native]
platform = native
platform_packages = platformio/toolchain-gccmingw32
extra_scripts = pre:scripts/native_toolchain.py
test_framework = unity
test_build_src = yes
build_unflags =
  -std=gnu++11
build_src_filter =
  +<log_format.cpp>
  +<com_protocol.cpp>
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Wpedantic
